import type { ModuleItem } from "@/types/module";
import type { Role } from "@/types/role";

const moduleCatalog: ModuleItem[] = [
  {
    id: "academic-attendance",
    title: "Attendance",
    description: "Track and review attendance records.",
    path: "/modules/academic/attendance",
    domain: "academic",
  },
  {
    id: "academic-curriculum",
    title: "Curriculum",
    description: "Manage curriculum structure and updates.",
    path: "/modules/academic/curriculum",
    domain: "academic",
  },
  {
    id: "academic-results",
    title: "Results",
    description: "Publish and review academic results.",
    path: "/modules/academic/results",
    domain: "academic",
  },
  {
    id: "academic-subjects",
    title: "Subjects",
    description: "Manage subjects and subject-level settings.",
    path: "/modules/academic/subjects",
    domain: "academic",
  },
  {
    id: "academic-timetable",
    title: "Timetable",
    description: "Build and maintain institutional timetable.",
    path: "/modules/academic/timetable",
    domain: "academic",
  },
  {
    id: "crm-admissions",
    title: "Admissions",
    description: "Oversee admission pipeline and cycles.",
    path: "/modules/crm/admissions",
    domain: "crm",
  },
  {
    id: "crm-applicants",
    title: "Applicants",
    description: "Manage leads and applicant records.",
    path: "/modules/crm/applicants",
    domain: "crm",
  },
  {
    id: "crm-counsellors",
    title: "Counsellors",
    description: "Track counsellor assignments and outcomes.",
    path: "/modules/crm/counsellors",
    domain: "crm",
  },
  {
    id: "faculty-assignments",
    title: "Assignments",
    description: "Create and review assignment workflows.",
    path: "/modules/faculty/assignments",
    domain: "faculty",
  },
  {
    id: "faculty-classes",
    title: "Classes",
    description: "Manage classes, sections, and scheduling.",
    path: "/modules/faculty/classes",
    domain: "faculty",
  },
  {
    id: "faculty-grading",
    title: "Grading",
    description: "Score, moderate, and finalize grades.",
    path: "/modules/faculty/grading",
    domain: "faculty",
  },
  {
    id: "finance-fees",
    title: "Fees",
    description: "Configure and monitor fee structures.",
    path: "/modules/finance/fees",
    domain: "finance",
  },
  {
    id: "finance-invoices",
    title: "Invoices",
    description: "Create and manage student invoices.",
    path: "/modules/finance/invoices",
    domain: "finance",
  },
  {
    id: "finance-payments",
    title: "Payments",
    description: "Reconcile transactions and receipts.",
    path: "/modules/finance/payments",
    domain: "finance",
  },
  {
    id: "management-departments",
    title: "Departments",
    description: "Manage department setup and ownership.",
    path: "/modules/management/departments",
    domain: "management",
  },
  {
    id: "management-reports",
    title: "Reports",
    description: "Generate performance and audit reports.",
    path: "/modules/management/reports",
    domain: "management",
  },
  {
    id: "management-roles",
    title: "Roles",
    description: "Define role hierarchy and access levels.",
    path: "/modules/management/roles",
    domain: "management",
  },
  {
    id: "student-attendance",
    title: "My Attendance",
    description: "View personal attendance and trends.",
    path: "/modules/student/attendance",
    domain: "student",
  },
  {
    id: "student-courses",
    title: "My Courses",
    description: "View enrolled courses and materials.",
    path: "/modules/student/courses",
    domain: "student",
  },
  {
    id: "student-profile",
    title: "My Profile",
    description: "Manage student profile and identity details.",
    path: "/modules/student/profile",
    domain: "student",
  },
  {
    id: "student-results",
    title: "My Results",
    description: "Check semester-wise academic outcomes.",
    path: "/modules/student/results",
    domain: "student",
  },
];

const domainsByRole: Record<Role, ModuleItem["domain"][]> = {
  admin: ["academic", "crm", "faculty", "finance", "management", "student"],
  collegeAdmin: ["academic", "crm", "finance", "management"],
  academicDirector: ["academic", "faculty", "management"],
  admissionDirector: ["crm"],
  admissionIncharge: ["crm"],
  admissionConsultant: ["crm"],
  admissionCounsellor: ["crm"],
  dean: ["academic", "faculty", "management"],
  hod: ["academic", "faculty"],
  faculty: ["academic", "faculty", "student"],
  student: ["student", "finance"],
  Applicant: ["crm"],
};

export const modulesByRole: Record<Role, ModuleItem[]> = {
  admin: moduleCatalog.filter((module) => domainsByRole.admin.includes(module.domain)),
  collegeAdmin: moduleCatalog.filter((module) => domainsByRole.collegeAdmin.includes(module.domain)),
  academicDirector: moduleCatalog.filter((module) => domainsByRole.academicDirector.includes(module.domain)),
  admissionDirector: moduleCatalog.filter((module) => domainsByRole.admissionDirector.includes(module.domain)),
  admissionIncharge: moduleCatalog.filter((module) => domainsByRole.admissionIncharge.includes(module.domain)),
  admissionConsultant: moduleCatalog.filter((module) => domainsByRole.admissionConsultant.includes(module.domain)),
  admissionCounsellor: moduleCatalog.filter((module) => domainsByRole.admissionCounsellor.includes(module.domain)),
  dean: moduleCatalog.filter((module) => domainsByRole.dean.includes(module.domain)),
  hod: moduleCatalog.filter((module) => domainsByRole.hod.includes(module.domain)),
  faculty: moduleCatalog.filter((module) => domainsByRole.faculty.includes(module.domain)),
  student: moduleCatalog.filter((module) => domainsByRole.student.includes(module.domain)),
  Applicant: moduleCatalog.filter((module) => domainsByRole.Applicant.includes(module.domain)),
};